### PR TITLE
roll arm32 builds back to alpine 3.12 to avoid time64 change

### LINKED ISSUE #127: nzbget segfaults with time64 on arm32
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

## Expected Behavior
nzbget should not segfault on arm32

## Current Behavior
nzbget segfaults when a time is encountered (when an nzb is in the queue or history).

## Steps to Reproduce

1. Add an nzb on an arm32 platform.

## Environment
**OS:** linux
**CPU architecture:** arm32
**How docker service was installed:** from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)

    docker run -d --name=nzbget --env=PUID=65534 --env=PGID=65534 --env=TZ=America/Chicago --volume=nzbget_data:/config -p 6789:6789 linuxserver/nzbget:latest

## Docker logs

    [cont-finish.d] executing container finish scripts...
    [cont-finish.d] done.
    [s6-finish] waiting for services.
    [s6-finish] sending all processes the TERM signal.
    [s6-finish] sending all processes the KILL signal and exiting.
    [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
    [s6-init] ensuring user provided files have correct perms...exited 0.
    [fix-attrs.d] applying ownership & permissions fixes...
    [fix-attrs.d] done.
    [cont-init.d] executing container initialization scripts...
    [cont-init.d] 01-envfile: executing... 
    [cont-init.d] 01-envfile: exited 0.
    [cont-init.d] 10-adduser: executing... 
    usermod: no changes
    -------------------------------------
              _         ()
             | |  ___   _    __
             | | / __| | |  /  \ 
             | | \__ \ | | | () |
             |_| |___/ |_|  \__/
    Brought to you by linuxserver.io
    -------------------------------------
    To support the app dev(s) visit:
    NZBGet: https://nzbget.net/donate
    To support LSIO projects visit:
    https://www.linuxserver.io/donate/
    -------------------------------------
    GID/UID
    -------------------------------------
    User uid:    65534
    User gid:    65534
    -------------------------------------
    [cont-init.d] 10-adduser: exited 0.
    [cont-init.d] 30-config: executing... 
    [cont-init.d] 30-config: exited 0.
    [cont-init.d] 99-custom-files: executing... 
    [custom-init] no custom files found exiting...
    [cont-init.d] 99-custom-files: exited 0.
    [cont-init.d] done.
    [services.d] starting services
    [services.d] done.

### PR DESCRIPTION
**Pull request by capntrips**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-nzbget/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Rolled buildstage back to alpine 3.12
Reverted #125 and installed py3-cryptography alpine package to avoid rust-lang/cargo#9187

## Benefits of this PR and context:

Fixes #127 and potentially #124

## How Has This Been Tested?

Deployed to Raspberry Pi 4 and tested basic functionality (download, check, repair, extract).

## Source / References:

[musl time64 Release Notes](https://musl.libc.org/time64.html)

### CODE REVIEW

**Comment by capntrips** [comment]
I'm happy to apply the py3-cryptography change to the other Dockerfiles, if it would be preferable.

**Comment by capntrips** [comment]
The issue I was having with building py cryptography must be something with my build system, as I had the same issue with alpine 3.13, and I see the weekly Jenkins build finished yesterday without issue.

Also, this may soon be redundant, and I appear to have fixed the time64 issue upstream. I submitted a pull request [here](nzbget/nzbget#742).

**Comment by tobbenb** [comment]
You are hitting the libseccomp error that has been an issue with focal on Ubuntu and on alpine after they started using 64bit time. So the best option is to update libseccomp or update to a 64bit OS.

**Comment by capntrips** [comment]
# date
    Fri Apr  9 09:28:14 CDT 2021

**Comment by Roxedus** [comment]
Just downgrading the buildtime should suffice.

**Review by Roxedus — APPROVED** [review]

**Pull request merged**
